version: '3.8'

services:
  oracle:
    # Imagen de Oracle XE (comunidad) optimizada; buena para desarrollo/local
    image: gvenzl/oracle-xe:23-slim
    container_name: oracle-xe-23
    environment:
      # Cambia la contraseña en .env.oracle si lo deseas
      - ORACLE_PASSWORD=${ORACLE_PASSWORD:-oraclepwd}
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET:-AL32UTF8}
      # La imagen crea por defecto una pluggable DB llamada XEPDB1
    ports:
      - "1521:1521"   # listener
      - "5500:5500"   # Enterprise Manager Express / OEM (si aplica)
    volumes:
      - ./data/oracle:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c \"echo 'select 1 from dual;' | sqlplus -s SYSTEM/${ORACLE_PASSWORD}@//127.0.0.1:1521/XEPDB1 >/dev/null 2>&1 || exit 1\""]
      interval: 30s
      timeout: 10s
      retries: 20

# Nota: usa `docker compose -f docker-compose.oracle.yml up -d` para levantar.
