const oracledb = require('oracledb')

;(async function () {
  const createSql = `
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM user_tables WHERE table_name = 'TENSORAPID') THEN
        NULL; -- placeholder
      END IF;
    END;
  `
  // We'll just try CREATE TABLE and ignore ORA-00955 if it exists
  const ddl = `CREATE TABLE TENSORAPID (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TESTNR VARCHAR2(32) NOT NULL,
    SEQNO NUMBER NOT NULL,
    NO_ NUMBER,
    TIEMPO_ROTURA NUMBER,
    FUERZA_B NUMBER,
    ELONGACION NUMBER,
    TENACIDAD NUMBER,
    TRABAJO NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_tensorapid_par FOREIGN KEY (TESTNR) REFERENCES Uster_PAR(TESTNR) ON DELETE CASCADE
  )`

  try {
    const conn = await oracledb.getConnection({
      user: process.env.ORACLE_USER || 'SYSTEM',
      password: process.env.ORACLE_PASSWORD || 'Alfa1984',
      connectString: process.env.ORACLE_CONNECTIONSTRING || 'localhost:1521/XE'
    })
    try {
      await conn.execute(ddl, [], { autoCommit: true })
      console.log('TENSORAPID created')
    } catch (e) {
      if (e.errorNum === 955) {
        console.log('TENSORAPID already exists - skipped')
      } else {
        console.error('create failed', e)
        process.exitCode = 2
      }
    } finally {
      await conn.close()
    }
  } catch (err) {
    console.error('connect failed', err)
    process.exitCode = 1
  }
})()
